name: Publish Docs

# Monthly, or on push
on:
  schedule:
      - cron: 0 11 1 * *
  push:
    branches:
      - master

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs: 
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

      - name: Install Docker
        shell: bash
        run: curl -s https://get.docker.com | bash
        
      - name: Build documentation
        shell: bash
        run: ./run.sh
        
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1.0.8
        with:
          name: gh-pages
          path: gen/build/docs/javadoc
        
      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v2.0.0
        with:
          # Name of the artifact to deploy
          artifact_name: gh-pages
